require_relative 'math_extensions'

require_relative 'core_ext/array'
require_relative 'core_ext/boolean'
require_relative 'core_ext/complex'
require_relative 'core_ext/enumerable'
require_relative 'core_ext/float'
require_relative 'core_ext/hash'
require_relative 'core_ext/integer'
require_relative 'core_ext/math'
require_relative 'core_ext/object'
require_relative 'core_ext/rational'
