require_relative 'core_ext/array'
require_relative 'core_ext/complex'
require_relative 'core_ext/float'
require_relative 'core_ext/hash'
require_relative 'core_ext/integer'
require_relative 'core_ext/rational'
